name: counter_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  flutter_bloc: ^8.1.3
  bloc_concurrency: ^0.2.2

  dio: ^5.3.2
  pretty_dio_logger: ^1.3.1
  flutter_dotenv: ^5.0.2

  geolocator: ^10.0.0

  freezed_annotation: ^2.4.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.3.1
  build_runner: ^2.2.0
  freezed: ^2.4.2

flutter:


  uses-material-design: true

  assets:
    - .env